# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b82e47be7eb5989c7df17cc05fb99e5154056d01f34b50244ac4852d3f7088faa734a6a2fc9019b37c899423bc6bd00cf0d36a497019864a8b7b501242b932e8

test:
  secret_key_base: bdeb11866c212aa2799bcb1767a0f24e5a856cbbdf7e73e9da1deb13713c61f88cd3c517d7b9bb4ab5d9bef464a25a47e36e4d2510e0137de91625bf4cdc3372

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
